get:
  tags:
    - FRSOpenAPI
  summary: ''
  description: getEnvironments
  operationId: getEnvironments
  responses:
    '201':
      description: ''
    '401':
      description: Not authenticated
  security:
    - oauth2:
        - 'write:pets'
        - 'read:pets'
